nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        # allow_origin: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        # allow_headers: ['Content-Type', 'Authorization']
        allow_headers: ['Accept','Authorization','Content-Type','X-Requested-With','X-XSRF-TOKEN']
        expose_headers: ['Link']
        # expose_headers: ['Accept','Authorization']
        max_age: 3600
    paths:
        # '^/': null
        '^/': ~
