# nelmio_cors:
#     defaults:
#         origin_regex: true
#         allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
#         # allow_origin: ['*']
#         allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
#         # allow_headers: ['Content-Type', 'Authorization']
#         allow_headers: ['Accept','Authorization','Content-Type','X-Requested-With','X-XSRF-TOKEN']
#         expose_headers: ['Link']
#         # expose_headers: ['Accept','Authorization']
#         max_age: 3600
#     paths:
#         # '^/': null
#         '^/': ~

nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        '^/apip/':
            origin_regex: true
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            # allow_headers: []
            max_age: 3600